### ISSUE TITLE
Does not work on Safari browser

### ISSUE THREAD

**Issue by Emasoft** [dutchcoders/elasticsearch-api.info#1]
The demo does not work on Safari browser. Nothing is displayed below the headers, even if I search for a string.

**Comment by edmarriner** [comment]
Also seems to be broken on mobile safari...

**Comment by styfle** [comment]
I am on my iOS 9.3 and nothing is showing up besides a table head.

**Comment by smotesko** [comment]
In Safari console I see a JS error:

```
ReferenceError: Can't find variable: fetch
```

The issue has an [answer on SO](http://stackoverflow.com/questions/35830202/fetch-not-defined-in-safari-referenceerror-cant-find-variable-fetch).

**Comment by nl5887** [comment]
Thx! Fixed this issue. window.fetch isn't implemented on safari browsers, 'whatwg-fetch' to the rescue.
