### ISSUE TITLE
Fork me on github banner covers part of the filter input field

### ISSUE THREAD

**Issue by mgingras** [dutchcoders/elasticsearch-api.info#2]
Clicking on the left ~100px of the filter input field actually clicks the fork me on github banner.

**Comment by mfn** [comment]
Can confirm, FF 47.0.1 on OSX 10.11.5

![snip20160711_1](https://cloud.githubusercontent.com/assets/87493/16720416/5fd61374-4736-11e6-8875-29b177ba040d.png)
